# -*- coding: utf-8 -*-
"""qibla

Qibla direction, Sun-Qibla alignment windows and a Sun/Qibla compass plot.

Originally generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1UK-U7P-Ab71HAPQJe0c4NNwdZ0TKaGxG

Amendments (see the summary that accompanies this file):
  * direction(): DMS conversion fixed (minutes were always 60, seconds 0).
  * direction(): quadrant table replaced by atan2, which fixes 180-degree errors
    for far-Pacific longitudes (e.g. Honolulu, Anchorage) and the crash when the
    longitude equals the Kaabah's. The same formula is used; only the quadrant
    resolution changed.
  * direction(): dead branches that referenced an undefined name removed.
  * Skyfield ephemeris/timescale are loaded once at import instead of on
    every dailyqibla() call.
  * qiblacompass(): draws the shadow azimuth (as documented in the README) and
    zero-pads the time in the title.
"""

import csv
import math
from dataclasses import dataclass
from datetime import timedelta, date

import numpy as np
from skyfield.api import load, wgs84
from skyfield import almanac

# ---------------------------------------------------------------------------
# Astronomical data (loaded once)
# ---------------------------------------------------------------------------
ts = load.timescale()
eph = load('de440s.bsp')
earth = eph['earth']
sun = eph['sun']

# Kaabah coordinates (decimal degrees)
KAABAH_LAT = 21.4225
KAABAH_LON = 39.8262


@dataclass(frozen=True)
class QiblaDirection:
    decimal: float  # decimal degrees, 0 <= value < 360 (clockwise from true North)
    degree: str     # same azimuth as "D° M′ S″"


def _to_dms(angle_deg: float) -> str:
    """Format an angle in decimal degrees as D° M′ S″, carrying rounding correctly."""
    total_seconds = round(angle_deg * 3600) % (360 * 3600)   # 359.99999° -> 0° 0′ 0″
    degrees, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{degrees}° {minutes}′ {seconds}″"


def direction(lat: float, long: float) -> QiblaDirection:
    """
    Great-circle Qibla azimuth (initial bearing to the Kaabah).

    lat  : observer latitude  (°N positive, °S negative)
    long : observer longitude (°E positive, °W negative)

    Returns QiblaDirection(decimal, degree) where `decimal` is the azimuth in
    [0, 360) measured clockwise from true North and `degree` is the same value
    formatted as D° M′ S″.
    """
    φ_Location = lat
    λ_Location = long
    φ_Kaabah = KAABAH_LAT
    λ_Kaabah = KAABAH_LON

    # Signed longitude difference (Kaabah - Location). Sine and cosine are
    # periodic, so no wrapping is needed and east/west is handled by the sign.
    Difference_Longitude = math.radians(λ_Kaabah - λ_Location)

    # Standing on the Kaabah itself: direction is undefined.
    if abs(φ_Location - φ_Kaabah) < 1e-9 and abs(λ_Location - λ_Kaabah) < 1e-9:
        raise ValueError("Location coincides with the Kaabah; Qibla direction is undefined.")

    #Calculation of Qibla Direction: tan(θ) = A / (B - C)
    A = math.sin(Difference_Longitude)
    B = math.cos(math.radians(φ_Location)) * math.tan(math.radians(φ_Kaabah))
    C = math.sin(math.radians(φ_Location)) * math.cos(Difference_Longitude)

    # atan2 keeps the signs of A and (B - C), so the correct quadrant
    # (UT / UB / ST / SB) comes out directly as an azimuth in [0, 360).
    azimuth_kiblat = math.degrees(math.atan2(A, B - C)) % 360.0

    return QiblaDirection(decimal=azimuth_kiblat, degree=_to_dms(azimuth_kiblat))


def dailyqibla(lat, long, ele, year, month, day, timezone, tolerance):
    """
    Find when the Sun's azimuth is aligned with (or opposite to) the Qibla
    direction on one local day. Only times with the Sun above the geometric
    horizon (altitude >= 0°) are counted.

    lat, long : observer latitude / longitude (degrees, N and E positive)
    ele       : elevation above sea level (m)
    year, month, day : local calendar date
    timezone  : UTC offset in hours (e.g. 8 for Malaysia)
    tolerance : half-width of the azimuth window (± degrees)

    Returns (qibla_text, opposite_text): two formatted strings.
    """
    # ---------- Inputs ----------
    lat_location = lat
    long_location = long

    # ---------- Setup ----------
    qibla_direction = direction(lat, long)
    qibla_az = qibla_direction.decimal

    # Opposite azimuth (wrapped)
    opp_az = (qibla_az - 180.0) % 360.0
    min_alt_deg = 0.0            # >0: strictly above geometric horizon
    # min_alt_deg = -0.833       # common sunrise standard incl. refraction + solar radius

    location = earth + wgs84.latlon(lat_location, long_location, elevation_m=ele)

    # Local-day window [00:00, 24:00) local
    t0 = ts.utc(year, month, day, 0 - timezone, 0, 0)
    t1 = ts.utc(year, month, day, 24 - timezone, 0, 0)

    def angular_diff_deg(a, b):
        """Smallest signed difference a-b on a circle (-180..+180]."""
        return ((a - b + 180.0) % 360.0) - 180.0

    def make_sector_fn(target_az_deg, tol_deg, min_alt):
        """Return a vectorized predicate for almanac.find_discrete()."""
        def in_sector(t):
            alt, az, _ = location.at(t).observe(sun).apparent().altaz()
            az_err = np.abs(angular_diff_deg(az.degrees, target_az_deg))
            return (alt.degrees >= min_alt) & (az_err <= tol_deg)
        # Hints for root finder
        in_sector.step_days = 0.001       # ~1.44 minutes
        in_sector.rough_period = 0.5      # ~12 hours between changes
        return in_sector

    def find_intervals(predicate, t0, t1):
        """Return list of (entry_time, exit_time) when predicate is True in [t0,t1]."""
        times, states = almanac.find_discrete(t0, t1, predicate)
        intervals = []

        # If already True at t0, prepend so we capture opening interval
        if predicate(t0):
            times = ts.tt_jd(np.insert(times.tt, 0, t0.tt))
            states = np.insert(states, 0, True)

        for i in range(len(times) - 1):
            if states[i]:
                intervals.append((times[i], times[i + 1]))

        # If last state remains True up to t1, close it
        if len(times) > 0 and states[-1]:
            intervals.append((times[-1], t1))

        return intervals

    def to_local(dt_utc):  # UTC -> local time (UTC + timezone hours)
        return dt_utc + timedelta(hours=timezone)

    # Build predicates
    fn_qibla = make_sector_fn(qibla_az, tolerance, min_alt_deg)
    fn_oppo = make_sector_fn(opp_az, tolerance, min_alt_deg)

    # Solve for both targets
    intervals_qibla = find_intervals(fn_qibla, t0, t1)
    intervals_oppo = find_intervals(fn_oppo, t0, t1)

    # ---------- Report ----------
    date_str = f"{year:04d}-{month:02d}-{day:02d}"

    def describe(label, target_az, intervals):
        """Return formatted string summary of the intervals for given azimuth."""
        output_lines = []
        if not intervals:
            return (f"[{label}] No Sun azimuth within {target_az:.2f}° ±{tolerance}° "
                    f"on {date_str}.")

        output_lines.append(f"[{label}] Sun azimuth ~ {target_az:.2f}° ±{tolerance}° "
                            f"on {date_str}.")

        for entry, exit_ in intervals:
            dt_start_local = to_local(entry.utc_datetime())
            dt_end_local = to_local(exit_.utc_datetime())
            output_lines.append(
                f"  • Entry ~ {dt_start_local:%H:%M:%S} | Exit ~ {dt_end_local:%H:%M:%S}  ")

        return "\n".join(output_lines)

    z = describe("QIBLA", qibla_az, intervals_qibla)
    y = describe("OPPOSITE (Qibla - 180°)", opp_az, intervals_oppo)

    return z, y


def multiday_qibla(lat, lon, ele, timezone, y, m, d_start, num_days, tolerance,
                   csv_filename=None):
    """
    Run dailyqibla() for a sequence of days and (optionally) save a CSV.
    - lat, lon, ele, timezone: observer
    - y, m, d_start: start date
    - num_days: how many days to compute (integer)
    - tolerance: azimuth tolerance (degrees)
    - csv_filename: if provided, save a CSV of windows per day
      (columns: Date, Label, Entry (Local), Exit (Local); "-" when no window)

    Prints a console summary and returns a list of dicts, one per day:
      {"date": "YYYY-MM-DD", "qibla": <str>, "opposite": <str>}
    """
    out = []

    # Prepare CSV if requested
    if csv_filename:
        with open(csv_filename, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["Date", "Label", "Entry (Local)", "Exit (Local)"])

    # Helper to parse the lines from dailyqibla() “describe(...)” strings
    def extract_rows(label, block_text):
        """
        From a describe() block, yield (label, entry, exit) tuples.
        Lines look like: "  • Entry ~ 14:23:11 | Exit ~ 14:39:45"
        """
        if not block_text or "No Sun azimuth within" in block_text:
            return []
        rows = []
        for line in block_text.splitlines():
            line = line.strip()
            if line.startswith("•"):
                parts = line.replace("•", "").replace("Entry ~", "").split("|")
                if len(parts) >= 2:
                    entry = parts[0].strip()
                    exit_ = parts[1].replace("Exit ~", "").strip()
                    rows.append((label, entry, exit_))
        return rows

    start_date = date(y, m, d_start)
    for i in range(num_days):
        this_date = start_date + timedelta(days=i)
        yy, mm, dd = this_date.year, this_date.month, this_date.day

        qibla_txt, opp_txt = dailyqibla(
            lat, lon, ele, yy, mm, dd, timezone, tolerance
        )

        out.append({
            "date": this_date.strftime("%Y-%m-%d"),
            "qibla": qibla_txt,
            "opposite": opp_txt
        })

        # Print compact console summary
        print(f"\n=== {this_date:%Y-%m-%d} ===")
        print(qibla_txt)
        print(opp_txt)

        # Append to CSV if requested
        if csv_filename:
            rows_q = extract_rows("QIBLA", qibla_txt)
            rows_o = extract_rows("OPPOSITE", opp_txt)
            with open(csv_filename, "a", newline="") as f:
                w = csv.writer(f)
                if rows_q:
                    for _, e, x in rows_q:
                        w.writerow([this_date.strftime("%Y-%m-%d"), "QIBLA", e, x])
                else:
                    w.writerow([this_date.strftime("%Y-%m-%d"), "QIBLA", "-", "-"])
                if rows_o:
                    for _, e, x in rows_o:
                        w.writerow([this_date.strftime("%Y-%m-%d"), "OPPOSITE", e, x])
                else:
                    w.writerow([this_date.strftime("%Y-%m-%d"), "OPPOSITE", "-", "-"])

    if csv_filename:
        print(f"\n✅ Saved multi-day Qibla windows to {csv_filename}")

    return out


def qiblacompass(latitude, longitude, year, month, day, timezone, time_hour, time_minute):
    """
    Polar compass (North at top, clockwise) showing the Qibla azimuth, the Sun's
    azimuth and, when the Sun is above the horizon, the azimuth of the shadow it
    casts (Sun azimuth + 180°). Shows the plot; returns None.

    latitude, longitude : observer coordinates (degrees, N and E positive)
    year, month, day    : local calendar date
    timezone            : UTC offset in hours
    time_hour, time_minute : local clock time
    """
    import matplotlib.pyplot as plt   # imported here so direction()/dailyqibla() need no plotting library

    # azimuth kiblat
    qibla_direction = direction(latitude, longitude)
    location = earth + wgs84.latlon(latitude, longitude, elevation_m=0)

    # Observation time (local -> UTC via timezone)
    t = ts.utc(year, month, day, time_hour - timezone, time_minute)
    sun_alt, sun_az, _ = location.at(t).observe(sun).apparent().altaz()

    fig, ax = plt.subplots(subplot_kw={'projection': 'polar'}, figsize=(8, 8))
    ax.set_theta_direction(-1)
    ax.set_theta_zero_location('N')

    # Plot Qibla Direction (blue dashed line)
    qibla_direction_rad = np.deg2rad(qibla_direction.decimal)
    ax.plot([0, qibla_direction_rad], [0, 1],
            label=f'Qibla: {qibla_direction.decimal:.2f}°',
            color='blue', linestyle='--', linewidth=2)

    # Plot Sun Azimuth (orange line)
    sun_direction_rad = np.deg2rad(sun_az.degrees)
    ax.plot([0, sun_direction_rad], [0, 1],
            label=f'Sun Az: {sun_az.degrees:.2f}°',
            color='orange', linestyle='-.', linewidth=2)

    # Plot Shadow Azimuth (opposite the Sun) - only meaningful while the Sun is up
    sun_up = sun_alt.degrees > 0
    if sun_up:
        shadow_az = (sun_az.degrees + 180.0) % 360.0
        ax.plot([0, np.deg2rad(shadow_az)], [0, 1],
                label=f'Shadow Az: {shadow_az:.2f}°',
                color='dimgray', linestyle=':', linewidth=2)

    note = "" if sun_up else "  (Sun below horizon - no shadow)"
    plt.title(f'Visualization of Qibla, Sun and Shadow Azimuth\n'
              f'Lat: {latitude}°  | Long: {longitude}° \n'
              f'{day} {month} {year}, {int(time_hour):02d}:{int(time_minute):02d} Local Time{note}\n',
              pad=20)
    plt.legend(loc='upper right')
    plt.show()
